// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ISContext))]
    [Migration("20210722103634_AddedSeedingOfProductsAndProductCategories")]
    partial class AddedSeedingOfProductsAndProductCategories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.AdditionalTables.ProductWithQuantity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductWithQuantity");
                });

            modelBuilder.Entity("Core.AdditionalTables.UserOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimePurchased")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrders");
                });

            modelBuilder.Entity("Core.AdditionalTables.UserShoppingCart", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserShoppingCart");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 0",
                            Price = 4016m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 1",
                            Price = 4072m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 2",
                            Price = 2153m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 3",
                            Price = 2245m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 4",
                            Price = 146m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 5",
                            Price = 4754m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 6",
                            Price = 1230m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 7",
                            Price = 496m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 8",
                            Price = 930m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 9",
                            Price = 144m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 10",
                            Price = 1488m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 11",
                            Price = 2904m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 12",
                            Price = 1463m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 13",
                            Price = 2225m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 14",
                            Price = 2065m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 15",
                            Price = 831m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 16",
                            Price = 3961m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 17",
                            Price = 1654m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 18",
                            Price = 2666m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 19",
                            Price = 2992m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 20",
                            Price = 3630m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 21",
                            Price = 1024m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 22",
                            Price = 4654m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 23",
                            Price = 315m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 24",
                            Price = 2491m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 25",
                            Price = 3469m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 26",
                            Price = 3052m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 27",
                            Price = 1511m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 28",
                            Price = 2387m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 29",
                            Price = 934m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 30",
                            Price = 4532m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 31",
                            Price = 1176m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 32",
                            Price = 1969m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 33",
                            Price = 1307m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 34",
                            Price = 4923m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 35",
                            Price = 1339m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 36",
                            Price = 1062m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 37",
                            Price = 1479m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 38",
                            Price = 746m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 39",
                            Price = 4052m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 40",
                            Price = 3815m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 41",
                            Price = 1567m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 42",
                            Price = 4259m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 43",
                            Price = 3793m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 44",
                            Price = 4307m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 45",
                            Price = 2919m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 46",
                            Price = 4486m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 47",
                            Price = 874m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 48",
                            Price = 3758m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 49",
                            Price = 4131m
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 50",
                            Price = 1294m
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 51",
                            Price = 3932m
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 52",
                            Price = 3026m
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 53",
                            Price = 2716m
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 54",
                            Price = 4080m
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 55",
                            Price = 2084m
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 56",
                            Price = 3505m
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 57",
                            Price = 930m
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 58",
                            Price = 3841m
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 59",
                            Price = 764m
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 60",
                            Price = 794m
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 61",
                            Price = 3806m
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 62",
                            Price = 2196m
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 63",
                            Price = 4083m
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 64",
                            Price = 4694m
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 65",
                            Price = 4399m
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 66",
                            Price = 27m
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 67",
                            Price = 4244m
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 68",
                            Price = 1389m
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 69",
                            Price = 4813m
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 70",
                            Price = 3856m
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 71",
                            Price = 1574m
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 5,
                            Description = "Food",
                            Name = "Food - 72",
                            Price = 4995m
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 73",
                            Price = 2701m
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 74",
                            Price = 3263m
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 75",
                            Price = 1155m
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 76",
                            Price = 852m
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 77",
                            Price = 4948m
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 78",
                            Price = 95m
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 79",
                            Price = 3659m
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 80",
                            Price = 3070m
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 81",
                            Price = 1270m
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 82",
                            Price = 1840m
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 83",
                            Price = 2343m
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 84",
                            Price = 3728m
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 85",
                            Price = 4687m
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 86",
                            Price = 2236m
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 87",
                            Price = 3340m
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 88",
                            Price = 1313m
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 89",
                            Price = 1932m
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 90",
                            Price = 1921m
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 91",
                            Price = 4219m
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 92",
                            Price = 1725m
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 93",
                            Price = 4069m
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 94",
                            Price = 2350m
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 95",
                            Price = 4097m
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 2,
                            Description = "TV",
                            Name = "TV - 96",
                            Price = 3458m
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 1,
                            Description = "Smartphone",
                            Name = "Smartphone - 97",
                            Price = 4263m
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 4,
                            Description = "Headphones",
                            Name = "Headphones - 98",
                            Price = 3186m
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 3,
                            Description = "Tool",
                            Name = "Tool - 99",
                            Price = 3995m
                        });
                });

            modelBuilder.Entity("Core.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Smartphone"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "TV"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Tool"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Headphones"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Food"
                        });
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "TestUser123",
                            Name = "TestUser",
                            PasswordHashed = "2rxmwCFIbkMfOyK51XDoMWdRQptnY3epAxNhJiWS4SYF+qIv",
                            Surname = "Doe"
                        });
                });

            modelBuilder.Entity("ProductWithQuantityUserOrder", b =>
                {
                    b.Property<int>("ProductsBoughtId")
                        .HasColumnType("int");

                    b.Property<int>("UserOrderId")
                        .HasColumnType("int");

                    b.HasKey("ProductsBoughtId", "UserOrderId");

                    b.HasIndex("UserOrderId");

                    b.ToTable("ProductWithQuantityUserOrder");
                });

            modelBuilder.Entity("Core.AdditionalTables.ProductWithQuantity", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Core.AdditionalTables.UserOrder", b =>
                {
                    b.HasOne("Core.Entities.Product", null)
                        .WithMany("UserOrder")
                        .HasForeignKey("ProductId");

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserOrder")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.AdditionalTables.UserShoppingCart", b =>
                {
                    b.HasOne("Core.Entities.Product", "Product")
                        .WithMany("UserShoppingCart")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.User", "User")
                        .WithMany("UserShoppingCart")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.ProductCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductWithQuantityUserOrder", b =>
                {
                    b.HasOne("Core.AdditionalTables.ProductWithQuantity", null)
                        .WithMany()
                        .HasForeignKey("ProductsBoughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.AdditionalTables.UserOrder", null)
                        .WithMany()
                        .HasForeignKey("UserOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Navigation("UserOrder");

                    b.Navigation("UserShoppingCart");
                });

            modelBuilder.Entity("Core.Entities.User", b =>
                {
                    b.Navigation("UserOrder");

                    b.Navigation("UserShoppingCart");
                });
#pragma warning restore 612, 618
        }
    }
}
